#########################################################################
# © Ronan LE MEILLAT 2023
# released under the GPLv3 terms
#########################################################################
{{- range .Values.ingress.hosts }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
      cert-manager.io/cluster-issuer: {{ .clusterIssuer }}
  labels:
    chart: "{{ $.Chart.Name }}-{{ $.Chart.Version | replace "+" "_" }}"
  name: {{ print "pretix-ingress-" .host  | replace "." "-" }}
spec:
  ingressClassName: {{ $.Values.ingress.ingressClassName }}
  rules:
    - host: {{.host }}
      http:
        paths:
          - backend:
              service:
                name: pretix-service
                port:
                  number: 80
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - {{ .host }}
      secretName: {{ print "pretix-cert-" .host  | replace "." "-" }}
---

{{- end }}
