#########################################################################
# © Ronan LE MEILLAT 2023
# released under the GPLv3 terms
#########################################################################
apiVersion: v1
kind: Secret
metadata:
  annotations: {}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
  name: postgres-credentials
data:
  {{- if eq .Values.databaseBackend "postgres" }}
  user: {{ b64enc .Values.postgresql.postgreuser }}
  password: {{ b64enc .Values.postgresql.postgrepass }}
  {{- end }}
  {{- if eq .Values.databaseBackend "cockroachdb" }}
  user: {{ b64enc .Values.cockroachdb.postgreuser }}
  password: {{ b64enc .Values.cockroachdb.postgrepass }}
  {{- end }}
type: Opaque