apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgresql.host }}
spec:
  selector:
    app: pgsql-server
  type: LoadBalancer
  ports:
    - name: pgsql-port
      protocol: TCP
      port: 5432
      targetPort: 5432